'use client';

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ProviderLayout from "./components/Provider";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Filmapp",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <html lang="en" className={darkMode ? "dark" : ""}>
      <body className={inter.className}>
        <ProviderLayout>
          <Header darkMode={darkMode} setDarkMode={setDarkMode} />
          {children}
          <Footer />
        </ProviderLayout>
      </body>
    </html>
  );
}
